#!/usr/bin/env python3
"""Input readers and KD conversion helpers for TolKinet."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np

from kd_to_txt import convert_kd
from kinet_common import Experiment


def _parse_float_cell(value: str, path: Path, line_number: int, column_number: int) -> float:
    """Parse one numeric cell from plain TXT or R write.csv2 output."""
    text = value.strip()
    if not text:
        raise ValueError(
            f"{path}: empty numeric value at line {line_number}, column {column_number}"
        )

    try:
        return float(text.replace(",", "."))
    except ValueError as exc:
        raise ValueError(
            f"{path}: cannot parse numeric value {value!r} "
            f"at line {line_number}, column {column_number}"
        ) from exc



def _read_numeric_table(path: Path, delimiter: str) -> np.ndarray:
    """Read a semicolon numeric table, including R write.csv2-style files."""
    rows: list[list[str]] = []
    with path.open(newline="", encoding="utf-8-sig") as file:
        for line_number, row in enumerate(csv.reader(file, delimiter=delimiter), start=1):
            if not row or all(not cell.strip() for cell in row):
                continue
            rows.append(row)

    if not rows:
        raise ValueError(f"{path}: file is empty")

    # R's write.csv2 writes an empty top-left header plus a row-name column.
    # For these files the first data row is duplicated as column names, so skip
    # the CSV header and remove the row-name column.
    has_r_row_names = rows[0][0].strip() == ""
    if has_r_row_names:
        rows = [row[1:] for row in rows[1:]]

    width = len(rows[0])
    if width < 2:
        raise ValueError(f"{path}: expected at least two columns")

    numeric_rows: list[list[float]] = []
    for line_offset, row in enumerate(rows, start=2 if has_r_row_names else 1):
        if len(row) != width:
            raise ValueError(
                f"{path}: line {line_offset} has {len(row)} columns, "
                f"expected {width}"
            )
        numeric_rows.append(
            [
                _parse_float_cell(value, path, line_offset, column_number)
                for column_number, value in enumerate(row, start=1)
            ]
        )

    return np.array(numeric_rows, dtype=float)



def read_experiment(path: str | Path, delimiter: str = ";") -> Experiment:
    """Read semicolon-separated spectrophotometry files.

    Supported layouts:

    - Plain TXT generated by kd_to_txt.py:
      0; t1; t2; ...
      lambda; A(lambda,t1); ...
    - R write.csv2 output with row names and comma decimals.
    """
    path = Path(path)
    data = _read_numeric_table(path, delimiter)
    t = data[0, 1:]
    wavelength = data[1:, 0]
    absorbance = data[1:, 1:]
    return Experiment(t=t, wavelength=wavelength, absorbance=absorbance)



def resolve_input_file(args: argparse.Namespace) -> Path:
    """Convert KD input files to text and return the file to analyze."""
    input_path = Path(args.input)
    if input_path.suffix.lower() != ".kd":
        return input_path

    output_path = input_path.with_name(f"{input_path.stem}-converted.txt")
    n_spectra, n_wavelengths, lambda_first, lambda_last = convert_kd(
        input_path,
        output_path,
        lambda_start=args.kd_lambda_start,
        lambda_step=args.kd_lambda_step,
    )

    print("KD file detected. Converted before analysis.")
    print(f"converted file: {output_path}")
    print(f"spectra / times: {n_spectra}")
    print(f"wavelength points: {n_wavelengths}")
    print(f"wavelength range: {lambda_first:g} - {lambda_last:g}")
    print()

    return output_path

